const mongoose = require('mongoose');
const Car = require('../models/Car-model');

mongoose.connect('mongodb://localhost:27017/cars', {
  useNewUrlParser: true,
  useUnifiedTopology: true
}).then(async () => {
  console.log('Connected to MongoDB');

 await Car.deleteMany({});
  const dummyCars = [
    {
      imageUrl:"/src/assets/car1.jpeg",  
      name: "Ford_Transit",
      pricePerDay: 97,
      currency: 'Euro',
      mileage: 'Unlimited',
      deposit: 500,
      class: 'Passenger Van',
      gearbox: 'Automatic',
      maxPassengers: 9,
      fuel: 'Diesel',
      fuelUsage: 8.2,
      engineCapacity: 2500,
      maxLuggage: 8,
      doors: 5,
      minDriverAge: 19,
      year: 2020,
      features: ['A/C', 'ABS', 'Air Bags', 'Central Locking', 'Electric Windows']
    },
    {
      imageUrl:"/src/assets/car1.jpeg",
      name: "Toyota_Corolla",
      pricePerDay: 65,
      currency: 'Euro',
      mileage: 'Unlimited',
      deposit: 300,
      class: 'Sedan',
      gearbox: 'Manual',
      maxPassengers: 5,
      fuel: 'Petrol',
      fuelUsage: 6.5,
      engineCapacity: 1600,
      maxLuggage: 4,
      doors: 4,
      minDriverAge: 21,
      year: 2019,
      features: ['A/C', 'Air Bags', 'Central Locking']
    },
    {
      imageUrl: "/src/assets/BugattiTourbillon.jpg",
      name: "Bugatti_Tourbillon",
      pricePerDay: 4500,
      currency: "Euro",
      mileage: "250 km/day",
      deposit: 10000,
      class: "Hypercar",
      gearbox: "Automatic",
      maxPassengers: 2,
      fuel: "Hybrid",
      fuelUsage: 12.0,
      engineCapacity: 8000,
      maxLuggage: 1,
      doors: 2,
      minDriverAge: 30,
      year: 2025,
      features: ["A/C", "Air Bags", "Central Locking", "Launch Control", "Adaptive Cruise Control", "Carbon Ceramic Brakes"]
    }
    
    ,
    {
      imageUrl:"/src/assets/car1.jpeg",
      name: "Honda_CR-V",
      pricePerDay: 80,
      currency: 'Euro',
      mileage: 'Unlimited',
      deposit: 400,
      class: 'SUV',
      gearbox: 'Automatic',
      maxPassengers: 7,
      fuel: 'Diesel',
      fuelUsage: 7.8,
      engineCapacity: 2200,
      maxLuggage: 6,
      doors: 5,
      minDriverAge: 23,
      year: 2021,
      features: ['A/C', 'ABS', 'Air Bags', 'Electric Windows']
    },
    {
      imageUrl: "/frontend/src/assets/bugatti_chiron.jpeg",
      name: "Bugatti_Chiron",
      pricePerDay: 6000,
      currency: "Euro",
      mileage: "250 km/day",
      deposit: 15000,
      class: "Hypercar",
      gearbox: "Automatic",
      maxPassengers: 2,
      fuel: "Petrol",
      fuelUsage: 15.0,
      engineCapacity: 8000,
      maxLuggage: 1,
      doors: 2,
      minDriverAge: 30,
      year: 2021,
      features: ["A/C", "Carbon Ceramic Brakes", "Launch Control"]
    },
    {
      imageUrl: "/frontend/src/assets/bugatti_tourbillon.jpeg",
      name: "Bugatti_Tourbillon",
      pricePerDay: 6500,
      currency: "Euro",
      mileage: "250 km/day",
      deposit: 16000,
      class: "Hypercar",
      gearbox: "Automatic",
      maxPassengers: 2,
      fuel: "Hybrid",
      fuelUsage: 12.0,
      engineCapacity: 8000,
      maxLuggage: 1,
      doors: 2,
      minDriverAge: 30,
      year: 2025,
      features: ["A/C", "Hybrid Drive", "Luxury Interior", "Digital Display"]
    },
    {
      imageUrl: "/src/assets/bugattiDivo.jpg",
      name: "Bugatti_Divo",
      pricePerDay: 6300,
      currency: "Euro",
      mileage: "200 km/day",
      deposit: 15500,
      class: "Hypercar",
      gearbox: "Automatic",
      maxPassengers: 2,
      fuel: "Petrol",
      fuelUsage: 16.0,
      engineCapacity: 8000,
      maxLuggage: 1,
      doors: 2,
      minDriverAge: 30,
      year: 2020,
      features: ["A/C", "Track-Tuned", "Luxury Finish"]
    },
    {
      imageUrl: "/frontend/src/assets/bugatti_mistral.jpeg",
      name: "Bugatti_Mistral",
      pricePerDay: 7000,
      currency: "Euro",
      mileage: "250 km/day",
      deposit: 17000,
      class: "Roadster",
      gearbox: "Automatic",
      maxPassengers: 2,
      fuel: "Petrol",
      fuelUsage: 14.5,
      engineCapacity: 8000,
      maxLuggage: 1,
      doors: 2,
      minDriverAge: 30,
      year: 2024,
      features: ["Convertible", "Advanced Cooling", "Sport Mode"]
    },
    {
      imageUrl: "/frontend/src/assets/bugatti_la_voiture_noire.jpeg",
      name: "Bugatti_La_Voiture_Noire",
      pricePerDay: 10000,
      currency: "Euro",
      mileage: "150 km/day",
      deposit: 20000,
      class: "Luxury Hypercar",
      gearbox: "Automatic",
      maxPassengers: 2,
      fuel: "Petrol",
      fuelUsage: 15.0,
      engineCapacity: 8000,
      maxLuggage: 1,
      doors: 2,
      minDriverAge: 35,
      year: 2021,
      features: ["Luxury Interior", "Custom Build", "Touchscreen Navigation"]
    },
    {
      imageUrl: "/frontend/src/assets/ferrari_sf90.jpeg",
      name: "Ferrari_SF90_Stradale",
      pricePerDay: 3500,
      currency: "Euro",
      mileage: "250 km/day",
      deposit: 9000,
      class: "Supercar",
      gearbox: "Automatic",
      maxPassengers: 2,
      fuel: "Hybrid",
      fuelUsage: 10.0,
      engineCapacity: 4000,
      maxLuggage: 2,
      doors: 2,
      minDriverAge: 28,
      year: 2023,
      features: ["Hybrid Drive", "A/C", "Touch Display"]
    },
    {
      imageUrl: "/frontend/src/assets/ferrari_488.jpeg",
      name: "Ferrari_488_GT",
      pricePerDay: 3000,
      currency: "Euro",
      mileage: "Unlimited",
      deposit: 8000,
      class: "Supercar",
      gearbox: "Automatic",
      maxPassengers: 2,
      fuel: "Petrol",
      fuelUsage: 11.5,
      engineCapacity: 3900,
      maxLuggage: 2,
      doors: 2,
      minDriverAge: 27,
      year: 2020,
      features: ["Air Bags", "Cruise Control", "Carbon Trim"]
    },
    {
      imageUrl: "/frontend/src/assets/ferrari_portofino.jpeg",
      name: "Ferrari_Portofino",
      pricePerDay: 2800,
      currency: "Euro",
      mileage: "Unlimited",
      deposit: 7500,
      class: "Convertible",
      gearbox: "Automatic",
      maxPassengers: 4,
      fuel: "Petrol",
      fuelUsage: 10.0,
      engineCapacity: 3855,
      maxLuggage: 2,
      doors: 2,
      minDriverAge: 27,
      year: 2021,
      features: ["Convertible Roof", "GPS", "Leather Seats"]
    },
    {
      imageUrl: "/frontend/src/assets/ferrari_f8.jpeg",
      name: "Ferrari_F8_Tributo",
      pricePerDay: 3200,
      currency: "Euro",
      mileage: "200 km/day",
      deposit: 8500,
      class: "Supercar",
      gearbox: "Automatic",
      maxPassengers: 2,
      fuel: "Petrol",
      fuelUsage: 12.0,
      engineCapacity: 3900,
      maxLuggage: 2,
      doors: 2,
      minDriverAge: 28,
      year: 2022,
      features: ["Sport Exhaust", "A/C", "Touchscreen"]
    },
    {
      imageUrl: "/frontend/src/assets/ferrari_laferrari.jpeg",
      name: "Ferrari_LaFerrari",
      pricePerDay: 5000,
      currency: "Euro",
      mileage: "200 km/day",
      deposit: 13000,
      class: "Hypercar",
      gearbox: "Automatic",
      maxPassengers: 2,
      fuel: "Hybrid",
      fuelUsage: 9.0,
      engineCapacity: 6300,
      maxLuggage: 1,
      doors: 2,
      minDriverAge: 30,
      year: 2019,
      features: ["Hybrid", "Launch Control", "Advanced Aero"]
    },
    {
      imageUrl: "/frontend/src/assets/classic_mustang.jpeg",
      name: "Ford_Mustang_1967",
      pricePerDay: 800,
      currency: "Euro",
      mileage: "Unlimited",
      deposit: 2500,
      class: "Classic",
      gearbox: "Manual",
      maxPassengers: 4,
      fuel: "Petrol",
      fuelUsage: 15.0,
      engineCapacity: 4700,
      maxLuggage: 2,
      doors: 2,
      minDriverAge: 25,
      year: 1967,
      features: ["Retro Interior", "A/C", "Original Sound"]
    },
    {
      imageUrl: "/frontend/src/assets/classic_porsche.jpeg",
      name: "Porsche_911_Classic",
      pricePerDay: 1000,
      currency: "Euro",
      mileage: "Unlimited",
      deposit: 3000,
      class: "Classic",
      gearbox: "Manual",
      maxPassengers: 2,
      fuel: "Petrol",
      fuelUsage: 12.0,
      engineCapacity: 3600,
      maxLuggage: 1,
      doors: 2,
      minDriverAge: 25,
      year: 1973,
      features: ["Classic Design", "Leather Interior"]
    },
    {
      imageUrl: "/frontend/src/assets/classic_e-type.jpeg",
      name: "Jaguar_E-Type",
      pricePerDay: 1200,
      currency: "Euro",
      mileage: "Unlimited",
      deposit: 3500,
      class: "Classic",
      gearbox: "Manual",
      maxPassengers: 2,
      fuel: "Petrol",
      fuelUsage: 13.0,
      engineCapacity: 4200,
      maxLuggage: 1,
      doors: 2,
      minDriverAge: 26,
      year: 1969,
      features: ["Wood Trim", "Classic Wheels"]
    },
    {
      imageUrl: "/frontend/src/assets/classic_mercedes.jpeg",
      name: "Mercedes_300SL",
      pricePerDay: 2000,
      currency: "Euro",
      mileage: "Unlimited",
      deposit: 5000,
      class: "Classic",
      gearbox: "Manual",
      maxPassengers: 2,
      fuel: "Petrol",
      fuelUsage: 12.0,
      engineCapacity: 3000,
      maxLuggage: 1,
      doors: 2,
      minDriverAge: 28,
      year: 1957,
      features: ["Gullwing Doors", "Leather Seats"]
    },
    {
      imageUrl: "/frontend/src/assets/classic_chevy_belair.jpeg",
      name: "Chevrolet_Bel_Air",
      pricePerDay: 700,
      currency: "Euro",
      mileage: "Unlimited",
      deposit: 2000,
      class: "Classic",
      gearbox: "Automatic",
      maxPassengers: 5,
      fuel: "Petrol",
      fuelUsage: 14.0,
      engineCapacity: 4600,
      maxLuggage: 3,
      doors: 4,
      minDriverAge: 25,
      year: 1955,
      features: ["Classic Radio", "A/C"]
    },
  ];
  

  await Car.insertMany(dummyCars);
  console.log('Dummy cars inserted');
  mongoose.connection.close();
}).catch(err => console.error(err));
